use_frameworks!

platform :ios, '8.0'

target 'WssNetworking_Example' do
  pod 'WssNetworking', :path => '../'

  target 'WssNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
